### ISSUE TITLE
Open up adapter API for addons

### ISSUE THREAD

**Issue by ShaneBeee** [GoingOffSkript/skript-variable-dump#1]
Hey... I just wanted to point out this resource is amazing, one issue I noticed is SkBee's NBT compounds are doing this:

<img width="1216" alt="Screen Shot 2021-05-12 at 10 35 14 AM" src="https://user-images.githubusercontent.com/20008482/118019356-c2423e00-b30d-11eb-87cd-b9b5ae689b51.png">

Now this is most likely an issue with the fact that NBT compounds are not yaml serializable, but maybe theres something you can do around this? Like a toString() kinda situation?!?! 

Just food for thought. 

Edit: 
For poops and hahas I did a lil test to visualize:
```vb
# {_n} being an NBT compound
set {item::test} to {_n}.toString()
```
Outcome:
<img width="1175" alt="Screen Shot 2021-05-12 at 10 43 02 AM" src="https://user-images.githubusercontent.com/20008482/118020437-eeaa8a00-b30e-11eb-8560-a6263cda8e55.png">

**Comment by ShaneBeee** [comment]
OH HEY... so I was peaking at your code:
https://github.com/GoingOffSkript/skript-variable-dump/blob/275b4d56a52f8877e63db86cf2028a2fe0b39bee/src/main/java/io/github/goingoffskript/skriptvariabledump/SkriptToYaml.java#L40

Any chance you could make this public?
If yes, I could add my own adapt in SkBee to handle NBT so you wouldn't have to do anything!

EDIT:
I did a test by making it public, and using it in my plugin:
<img width="755" alt="Screen Shot 2021-05-12 at 11 05 19 AM" src="https://user-images.githubusercontent.com/20008482/118023128-06cfd880-b312-11eb-8d85-72421cbad9b0.png">

Seems to work very nicely:
<img width="1242" alt="Screen Shot 2021-05-12 at 11 04 30 AM" src="https://user-images.githubusercontent.com/20008482/118023141-0afbf600-b312-11eb-9884-36271c22819f.png">

**Comment by RezzedUp** [comment]
Ah yeah, variable dumping works *mostly* out of the box because most Skript data is either Java primitives or Bukkit types that have predefined config serializers. I added some "yaml adapters" for a few common Skript-specific data types (as you found poking through the code) but there certainly isn't any addon support... yet!

I suppose there's no harm in opening up the API for addons that would like to add adapters for their data types.

**Comment by RezzedUp** [comment]
Added in release v0.0.2.
